library(igraph)
g<-read.graph('higgy.csv', format="ncol")
#g<-read.graph('Padgett.csv', format="ncol")
plot(g, layout= layout.fruchterman.reingold)
ecount(g)
vcount(g)
V(g)
# tkplot(g, layout = layout.circle)
degree(g)
betweenness(g)
plot(degree(g))
